/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    packages: Package;
    addons: Addon;
    'frame-styles': FrameStyle;
    leads: Lead;
    gallery: Gallery;
    faqs: Faq;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    addons: AddonsSelect<false> | AddonsSelect<true>;
    'frame-styles': FrameStylesSelect<false> | FrameStylesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  name: string;
  /**
   * URL-safe id, e.g. premium
   */
  slug: string;
  /**
   * Internal only (cents). Never shown on the public site.
   */
  basePrice: number;
  /**
   * Public range only, e.g. $495–$695 or Custom quote
   */
  priceRange?: string | null;
  /**
   * Short frame line for cards, e.g. 120 guest frames
   */
  frameSummary?: string | null;
  description: string;
  /**
   * Emoji shown on package cards
   */
  icon?: string | null;
  features: {
    item: string;
    id?: string | null;
  }[];
  notIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  popular?: boolean | null;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
  id: number;
  name: string;
  slug: string;
  /**
   * Price in cents per unit
   */
  price: number;
  pricingUnit: 'fixed' | 'per_frame' | 'per_pack' | 'per_hour' | 'per_km';
  description?: string | null;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frame styles shown on the website (up to 5 active).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frame-styles".
 */
export interface FrameStyle {
  id: number;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  /**
   * Example personalized text shown on the sample frame
   */
  sampleMessage: string;
  /**
   * Public path e.g. /brand/style-romance.png
   */
  imagePath: string;
  /**
   * Customer-facing color names (do not include material jargon). Max 4.
   */
  plaColors: {
    /**
     * e.g. Pastel Yellow
     */
    name: string;
    /**
     * Approximate swatch hex, e.g. #E8D36A
     */
    hex: string;
    role: 'base' | 'accent' | 'text' | 'detail';
    id?: string | null;
  }[];
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  serviceType?: ('frames' | 'stickers' | 'both') | null;
  name: string;
  email: string;
  phone: string;
  eventType: string;
  eventDate: string;
  guestCount?: string | null;
  message?: string | null;
  package?: (number | null) | Package;
  /**
   * Snapshot of package name at submit time
   */
  packageName?: string | null;
  frameStyle?: (number | null) | FrameStyle;
  /**
   * Snapshot of frame style at submit time
   */
  frameStyleName?: string | null;
  /**
   * Frame color list snapshot
   */
  frameStyleColors?: string | null;
  /**
   * Polaroid (classic) or 4×6 (premium size)
   */
  frameFormat?: ('polaroid' | '4x6') | null;
  /**
   * Snapshot label for emails
   */
  frameFormatLabel?: string | null;
  /**
   * Package base price in cents at submit time
   */
  packagePrice?: number | null;
  selectedAddOns?:
    | {
        addonId?: string | null;
        name: string;
        price: number;
        pricingUnit?: string | null;
        quantity: number;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Total estimate in cents
   */
  estimatedTotal: number;
  status?: ('new' | 'contacted' | 'booked' | 'closed') | null;
  notes?: string | null;
  inquiryId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  caption?: string | null;
  eventType?: ('wedding' | 'corporate' | 'birthday' | 'graduation' | 'anniversary' | 'other') | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts and articles for SEO and traffic.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL path — e.g. wedding-keepsake-ideas
   */
  slug: string;
  /**
   * Short summary for cards and search results.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional hero image for the post.
   */
  featuredImage?: (number | null) | Media;
  category: 'tips' | 'events' | 'studio' | 'trends';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * SEO meta description (max 160 characters).
   */
  metaDescription?: string | null;
  source?: ('admin' | 'openclaw' | 'seed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'addons';
        value: number | Addon;
      } | null)
    | ({
        relationTo: 'frame-styles';
        value: number | FrameStyle;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  basePrice?: T;
  priceRange?: T;
  frameSummary?: T;
  description?: T;
  icon?: T;
  features?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  popular?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  price?: T;
  pricingUnit?: T;
  description?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frame-styles_select".
 */
export interface FrameStylesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  sampleMessage?: T;
  imagePath?: T;
  plaColors?:
    | T
    | {
        name?: T;
        hex?: T;
        role?: T;
        id?: T;
      };
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  serviceType?: T;
  name?: T;
  email?: T;
  phone?: T;
  eventType?: T;
  eventDate?: T;
  guestCount?: T;
  message?: T;
  package?: T;
  packageName?: T;
  frameStyle?: T;
  frameStyleName?: T;
  frameStyleColors?: T;
  frameFormat?: T;
  frameFormatLabel?: T;
  packagePrice?: T;
  selectedAddOns?:
    | T
    | {
        addonId?: T;
        name?: T;
        price?: T;
        pricingUnit?: T;
        quantity?: T;
        lineTotal?: T;
        id?: T;
      };
  estimatedTotal?: T;
  status?: T;
  notes?: T;
  inquiryId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  eventType?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  status?: T;
  publishedAt?: T;
  metaDescription?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone?: string | null;
  email?: string | null;
  serviceArea?: string | null;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  /**
   * Shown in the home trust bar when that section is enabled.
   */
  trustBadges?:
    | {
        icon: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only shown when “Show testimonials” is enabled.
   */
  testimonials?:
    | {
        text: string;
        author: string;
        id?: string | null;
      }[]
    | null;
  showAboutPage?: boolean | null;
  showPackagesPage?: boolean | null;
  showStickersPage?: boolean | null;
  showGalleryPage?: boolean | null;
  showBlogPage?: boolean | null;
  showFaqPage?: boolean | null;
  showContactPage?: boolean | null;
  showQuotePage?: boolean | null;
  showTrustBar?: boolean | null;
  showStylesSection?: boolean | null;
  showProductStory?: boolean | null;
  showHowItWorks?: boolean | null;
  showPackagesSection?: boolean | null;
  showLifestyleBanner?: boolean | null;
  showGalleryPreview?: boolean | null;
  showBlogPreview?: boolean | null;
  /**
   * Keep off until you have real reviews to publish.
   */
  showTestimonials?: boolean | null;
  showFinalCta?: boolean | null;
  /**
   * Usually leave off — quantities are better on Packages / Quote.
   */
  showFrameCountOnHome?: boolean | null;
  /**
   * When off, package price ranges are hidden. Leads still request a custom quote.
   */
  showPricing?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  serviceArea?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  trustBadges?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        text?: T;
        author?: T;
        id?: T;
      };
  showAboutPage?: T;
  showPackagesPage?: T;
  showStickersPage?: T;
  showGalleryPage?: T;
  showBlogPage?: T;
  showFaqPage?: T;
  showContactPage?: T;
  showQuotePage?: T;
  showTrustBar?: T;
  showStylesSection?: T;
  showProductStory?: T;
  showHowItWorks?: T;
  showPackagesSection?: T;
  showLifestyleBanner?: T;
  showGalleryPreview?: T;
  showBlogPreview?: T;
  showTestimonials?: T;
  showFinalCta?: T;
  showFrameCountOnHome?: T;
  showPricing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}